baseurl: "https://www.noamross.net/"
languageCode: "en-us"
title: "noamross.net"
enableEmoji: true
pygmentsCodefences: true
pygmentsStyle: "lovelace"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
canonifyURLs: true
permalinks:
  musings: "/:year/:month/:day/:slug/"
  archives: "/archives/:filename/"

author:
  name: "Noam Ross"
  email: "noam.ross@gmail.com"
params:
  title: "Dr. Noam Ross"
  copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
  description: "Principal Scientist, Computational Research, @EcoHealthNYC. @rOpenSci Leadership. Disease ecology, #rstats, open science, fun, love, progress + justice. He/him"
rssLimit: 50
