baseurl: "https://www.noamross.net/"
languageCode: "en-us"
title: "noamross.net"
enableEmoji: true
pygmentsCodefences: true
pygmentsStyle: "lovelace"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
canonifyURLs: true
permalinks:
  musings: "/:year/:month/:day/:slug/"
  archives: "/archives/:filename/"
disableKinds:
  - "taxonomy"
  - "taxonomyTerm"

author:
  name: "Noam Ross"
  email: "noam.ross@gmail.com"
params:
  title: "Dr. Noam Ross"
  copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
  description: "Senior Research Scientist, @EcoHealthNYC. Editor, @rOpenSci. Disease and theoretical ecology, #rstats, open science + code. Also fun, love, progress + justice."
rssLimit: 50
