version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: noamross/noamrossnet:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps2-$R_VERSION-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
            - deps2-$R_VERSION-{{ .Branch }}
            - deps2-$R_VERSION
      - run:
          name: "Install Dependencies"
          command: |
            ./install.sh
      - run:
          name: "Get ORCiD Records"
          command: |
            Rscript scripts/get-orcid-data.R || true
      - run:
          name: "Render R Markdown"
          command: |
            Rscript -e "blogdown::build_site(run_hugo = FALSE)" || true
      - run:
          name: "Build Hugo Site"
          command: |
            export HUGO_ASSET_BASEURL=https://cdn.jsdelivr.net/gh/noamross/noamross.net@${CIRCLE_SHA1}/static/
            echo $HUGO_ASSET_BASEURL
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              hugo --cacheDir `pwd`/hugo_cache
            else
              hugo --buildDrafts --buildFuture --baseURL https://www.noamross.net/branch/${CIRCLE_BRANCH}/ --cacheDir `pwd`/hugo_cache
            fi
      - add_ssh_keys:
          fingerprints:
            - "7c:cf:69:c8:f8:86:24:81:66:70:a6:18:72:1f:ca:07"
      - deploy:
          name: "Rsync to site"
          command: |
            ssh-keyscan -t "ecdsa" ssh.phx.nearlyfreespeech.net >> ~/.ssh/known_hosts
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               rsync -avz --delete public/ noamross_noamross@ssh.phx.nearlyfreespeech.net:/home/public/ --exclude=branch --exclude=assets --exclude=awstats
            else
               rsync -avz --delete public/ noamross_noamross@ssh.phx.nearlyfreespeech.net:/home/public/branch/${CIRCLE_BRANCH} --exclude=assets --exclude=.htaccess --exclude=robots.txt --exclude=awstats
            fi
      - run:
          name: "Calculate Stats"
          command: |
            ssh noamross_noamross@ssh.phx.nearlyfreespeech.net "/usr/local/www/awstats/tools/awstats_buildstaticpages.pl -config=nfsn -update -dir=/home/public/awstats && cd /home/public/awstats && ln -sf awstats.nfsn.html index.html"
      - save_cache:
          key: deps2-$R_VERSION-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - "/usr/local/lib/R/site-library"
            - "blogdown"
            - "hugo_cache"
  calc_stats:
    working_directory: ~/main
    docker:
      - image: krlmlr/debian-ssh:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7c:cf:69:c8:f8:86:24:81:66:70:a6:18:72:1f:ca:07"
      - run:
          name: "Calculate Stats"
          command: |
            ssh-keyscan -t "ecdsa" ssh.phx.nearlyfreespeech.net >> ~/.ssh/known_hosts
            ssh noamross_noamross@ssh.phx.nearlyfreespeech.net "/usr/local/www/awstats/tools/awstats_buildstaticpages.pl -config=nfsn -update -dir=/home/public/awstats && cd /home/public/awstats && ln -sf awstats.nfsn.html index.html"
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
#  hourly:
#    triggers:
#      - schedule:
#          cron: "45 * * * *"
#          filters:
#              branches:
#                only:
#                  - master
#    jobs:
#       - calc_stats
#
